#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

#define HAVE_EMBEDDED_TIME_MS 1
#define HAVE_BTSTACK_STDIN 1
#define ENABLE_LOG_INFO 1
#define ENABLE_LOG_ERROR 1
#define ENABLE_PRINTF 1
#define ENABLE_BLE 1
#define ENABLE_CLASSIC 0

/* Use malloc-backed buffers so BTstack can grow its ATT database as needed. */
#define HAVE_MALLOC 1
#define MAX_ATT_DB_SIZE 512

#define MAX_NR_GATT_CLIENTS 1
#define MAX_NR_HCI_CONNECTIONS 1
#define MAX_NR_LE_DEVICE_DB_ENTRIES 2
#define MAX_NR_SM_LOOKUP_ENTRIES 2
#define MAX_NR_ALLOWLIST_ENTRIES 16
#define MAX_NR_BLE_SERVICES 1
#define MAX_NR_BLE_CHARACTERISTICS 1
#define MAX_NR_BLE_DESCRIPTORS 1
#define MAX_NR_BLE_CLIENTS 1
#define MAX_NR_BLE_ADVERTISEMENTS 1
#define MAX_NR_BLE_GATT_SUBSCRIPTIONS 1
#define MAX_NR_BLE_GATT_CLIENTS 1
#define MAX_NR_BLUETOOTH_SMART_DEVICE_CONNECTIONS 1
#define HCI_ACL_PAYLOAD_SIZE 1024
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define MAX_NR_BTSTACK_LINK_KEYS 2
#define MAX_NR_L2CAP_CHANNELS 1
#define MAX_NR_CONTROLLER_COMMANDS 16
#endif